<a href="https://colab.research.google.com/github/Narmadakumbhkar/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 #Numpy in python

In [ ]:
#single dimensional array

import numpy as np
n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [ ]:
#multi dimensional array

import numpy as np
n2=np.array([[10,20,30,40],[40,30,20,10]])
n2

array([[10, 20, 30, 40],
       [40, 30, 20, 10]])

In [ ]:
import numpy as np
l1=[10,20,30,40]
np.array(l1)
n1

array([10, 20, 30, 40])

In [ ]:
type(n1)

numpy.ndarray

In [ ]:
np.array([[1,2,3,4],[4,3,2,1]])


array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [ ]:
n2
type(n2)

numpy.ndarray

In [ ]:
#initializing numpy array with zeros

import numpy as np
n1=np.zeros((1,2))
n1

array([[0., 0.]])

In [ ]:
n2=np.zeros([5,5])
n2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
n3=np.zeros((2,3))
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# initializing numpy array with same number

import numpy as np
n1=np.full((2,3),10)
n1

array([[10, 10, 10],
       [10, 10, 10]])

In [ ]:
#initializing numpy array with a range

import numpy as np
n1=np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
import numpy as np
n2=np.arange(10,50,5)
n2

array([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:

n3=np.arange(1,100,2)
n3

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [ ]:
#initializaing numpy array with random number

import numpy as np
a1=np.random.randint(1,100,5)
a1


array([27, 48, 18, 36, 55])

In [ ]:
a2=np.random.randint(1,100,5)
a2

array([11, 75, 73, 90, 44])

In [ ]:
#checking the shape of numpy array

import numpy as np
n1=np.array([[1,2,3],[4,5,6]])
n1.shape

(2, 3)

In [ ]:
n3=np.array([[2,3,4,5],[6,7,8,9],[11,33,22,44]])
n3.shape

(3, 4)

In [ ]:
n3.shape=(4,3)
n3.shape

(4, 3)

In [ ]:
import numpy as np
z1= np.array([[1,2,3,4,],[5,6,7,8]])
z1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
z1.shape=(4,2)
z1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
z1.shape = (8,1)
z1

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [ ]:
#vstack()

import numpy as np
n1=np.array([10,20,30])
n2=np.array([40,50,60])
n3=np.array([70,80,90])

np.vstack(((n1,n2,n3)))

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
#hstack()

import numpy as np
n1=np.array([1,2,3,4])
n2=np.array([5,6,7,8])
np.hstack((n1,n2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
#column_stack()

import numpy as np
n1=np.array([11,22,33,44,55])
n2=np.array([66,77,88,99,00])
np.column_stack((n1,n2))

array([[11, 66],
       [22, 77],
       [33, 88],
       [44, 99],
       [55,  0]])

In [ ]:
import numpy as np
np.array([1,2,3,4,5,6])



array([1, 2, 3, 4, 5, 6])

In [ ]:
import numpy as np
print(np.__version__)
print(type(array))

1.21.5
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
arr=np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [ ]:
#intersect1d

import numpy as np
n1=np.array([10,20,30,40,50,60])
n2=np.array([50,60,70,80,90])
np.intersect1d(n1,n2)


array([50, 60])

In [ ]:
import numpy as np
n1=np.array([10,20,30,40,50,60])
n2=np.array([50,60,70,80,90])
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [ ]:
import numpy as np
n1=np.array([10,20,30,40,50,60])
n2=np.array([50,60,70,80,90])
np.setdiff1d(n2,n1)

array([70, 80, 90])

In [ ]:
import numpy as np
n1=np.array([10,30])
n2=np.array([20,40])
np.sum([n1,n2])

100

In [ ]:
import numpy as np
n1=np.array([11.2,22.2])
n2=np.array([10.1,11.4])
np.sum([n1,n2])

54.9

In [ ]:
np.sum([n1,n2],axis=0)

array([30, 70])

In [ ]:
np.sum([n1,n2],axis=1)

array([33.4, 21.5])

In [ ]:
# Basic addition
import numpy as np
n1=np.array([10,20,30])
n1=n1+1
n1


array([11, 21, 31])

In [ ]:
import numpy as np
n1=np.array([10,20,30])
n1=n1+2
n1

array([12, 22, 32])

In [ ]:
#Basic multiplication

import numpy as np
n1=np.array([10,20,30])
n1=n1*2
n1 

array([20, 40, 60])

In [ ]:
import numpy as np
n1=np.array([10,20,30])
n1=n1*1.1
n1 

array([11., 22., 33.])

In [ ]:
#Basaic subtraction

import numpy as np
n1=np.array([10,20,30,40,50])
n1=n1-5
n1

array([ 5, 15, 25, 35, 45])

In [ ]:
#Basic division

import numpy as np
n1=np.array([10,20,30,40,50,60])
n1=n1/2
n1

array([ 5., 10., 15., 20., 25., 30.])

In [ ]:
import numpy as np
n1=np.array([10,20,30,40,50,60])
n1=n1//2
n1

array([ 5, 10, 15, 20, 25, 30])

In [ ]:
import numpy as np
n1=np.array([10,20,30,40,50,60])
n1=n1%3
n1

array([1, 2, 0, 1, 2, 0])

In [ ]:
import numpy as np
n1=np.array([10,20,30,40,50,60])
n1=n1**2
n1

array([ 100,  400,  900, 1600, 2500, 3600])

In [ ]:
#mean
import numpy as np
n1=np.array([10,20,30,40,50,60])
np.mean(n1)

35.0

In [ ]:
#median
import numpy as np
n1=np.array([10,20,30,40,50,60])
np.median(n1)

35.0

In [ ]:
import numpy as np
n1=np.array([23,56,78,98])
np.std(n1)

1.854723699099141

In [ ]:
import numpy as np
n1=np.random.randint(1,50,10)
n1

array([ 4, 41, 29, 31, 34, 47, 28, 23, 29,  2])

In [ ]:
np.mean(n1)

26.8

In [ ]:
#numpy save $ load

# saving numpy array
import numpy as np
n1=np.array([10,20,30,40,50])
np.save('my_numpy',n1)

In [ ]:
n1=np.load('my_numpy.npy')
n1

array([10, 20, 30, 40, 50])

In [ ]:
n1

array([10, 20, 30, 40, 50])

In [ ]:
np.save('myarray',n1)
new_n1=np.load('myarray.npy')
new_n1

array([10, 20, 30, 40, 50])

In [ ]:
# eye()
import numpy as np
arr=np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
import numpy as np
arr=np.eye(3,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
arr=np.eye(3,3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr=np.eye(4,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# diag()
import numpy as np
arr=np.diag((1,3,5,7))
arr

array([[1, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 7]])

In [ ]:
arr=np.diag([2,4,6,8])
arr

array([[2, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])

In [ ]:
# randint()
import numpy as np
arr=np.random.randint(1,10,3)
arr


array([8, 8, 6])

In [ ]:
# rand()          ## random values between 0 t0 1
import numpy as np
arr=np.random.rand(5)
arr

array([0.25284452, 0.8774609 , 0.98252734, 0.45934656, 0.3337363 ])

In [ ]:
# randn()   ##random values close to 0 (positive,negative)
import numpy as np
arr=np.random.randn(3)
arr


array([0.34059924, 1.6866111 , 0.82973195])

In [ ]:
arr=np.random.randn(4)
arr

array([-0.67959482, -1.00001914, -2.18023738,  1.30589681])

In [ ]:
#arr.reshape
import numpy as np
arr=np.random.randint(1,100,12)
arr=arr.reshape(3,4)
arr

array([[65,  8, 73, 10],
       [33, 55, 94, 43],
       [62, 93, 92, 59]])

In [ ]:
import numpy as np
arr=np.random.randint(3,200,6)
arr=arr.reshape(2,3)
arr

array([[31, 77,  9],
       [51, 94, 46]])